# Built-in test to check that the primary key is unique and not null

version: 2

models:
  - name: slv_processed_trials
    description: "Clinical trials (1 row per NCT study)."
    columns:
      - name: nct_id
        tests:
          - not_null
          - unique
