services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clinical_trials
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: orchestrator
    depends_on:
      - postgres
    environment:
      TZ: Europe/Madrid
      SCHEDULE_CRON: "0 7 * * *"
      RUN_ON_START: "true"
    volumes:
      - ../ingestion:/usr/app/ingestion
      - ../dbt:/usr/app
      - ./logs:/app/logs
    restart: "no"
    command: ["python", "/app/orchestrate.py"]

volumes:
  pg_data:
